spring.application.name=weatherApp
weather.api.key=9aa5bac423f646e59a094707261303
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.forecast.url=http://api.weatherapi.com/v1/forecast.json